language: python
python:
    - "2.7"

install:
    - make build

script:
    - echo "TODO"

deploy:
  provider: pypi
  user: anfederico
  password:
    secure: my_secure_password
  on:
    tags: true
    branch: master
  
